version: "3"

services:
  app:
    build: .
    environment:
      DB_URI: "${DB_URI}"
      DB_NAME: "${DB_NAME}"
    depends_on:
      - db
    depends_on:
      - db
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

  db:
    image: mongo